### ISSUE TITLE
How to generate a vector that stores interface{} ?

### ISSUE THREAD

**Issue by rtheunissen** [tobgu/peds#8]
The vector specification appears to only support int (it only checks for alphanumeric and assumes a length of 3, ie "int"). I'm trying to run some benchmarks against other vectors that all store `interface{}` so to level the playing field I would like to include _peds_ in that benchmark, but I can only do so if I can generate a generic implementation.

**Comment by tobgu** [comment]
Hi!

It does check for a alphanumeric string as type name which is perhaps a bit on the restrictive side. There shouldn't be anything checking that the length of the type name is three chararcter long though. The length comparison is to check that the vector specification conainst all expected parts (a name and a type).

To work around the alphanumeric restriction for your tests it should be possible for you to either create a new type which is an empty interface and give it a alphanumeric range or even doing the same with a type alias and refer to the new name when generating the vector implementation. Eg.
```go
type MyEmptyIf interface{}
// or, with a type alias
type MyEmptyIf = interface{}
```

Hope this helps! Let me know if you have additional questions!

**Comment by rtheunissen** [comment]
That helps, thank you very much. The alias approach is great. :+1:

**Comment by tobgu** [comment]
Great! I'd be happy to learn about the outcomes of any perf comparisons!
